function printResultsPerIteration(FileID,Network,Method)


if ~strcmp(Method,'Default') && ~strcmp(Method,'BN')
fprintf(FileID,'%-10s &%-10s & %-10s & %-10.4f  & %-10.4f & %-10.4f & %-10.4f &  %-10.4f & %-10.4f &  %-10.2f & %-10.2f  &%-10.2f  \n',...
    '13-bus',Network.RegulatorType, Method,Network.Optimization.OptimalValue,...
    Network.Solution.OptimalValue, ...
   100*(abs(Network.Solution.OptimalValue-Network.Optimization.OptimalValue))./Network.Optimization.OptimalValue,...
   Network.Solution.vMin,...
    Network.Solution.vMax,...
    Network.Solution.VoltageUnbalanceIndex,Network.Solution.MaxAngle, Network.Optimization.L2L1,    Network.Optimization.TimeInfo(4));
 
elseif strcmp(Method,'BN')
    
fprintf(FileID,'%-10s &%-10s & %-10s & %-10.4f  & %-10.4f & %-10.4f & %-10.4f &  %-10.4f & %-10.4f &  %-10.2f & %-10.2f &%-10.2f  \n',...
    '13-bus',Network.RegulatorType, Method,Network.Optimization.OptimalValue,...
    Network.Solution.OptimalValue, ...
   100*(abs(Network.Solution.OptimalValue-Network.Optimization.OptimalValue))./Network.Optimization.OptimalValue,...
   Network.Solution.vMin,...
    Network.Solution.vMax,...
    Network.Solution.VoltageUnbalanceIndex,Network.Solution.MaxAngle,NaN, Network.Optimization.TimeInfo(1));
    
else
    
fprintf(FileID,'%-10s &%-10s & %-10s & %-10.4f  & %-10.4f & %-10.4f & %-10.4f &  %-10.4f & %-10.4f &  %-10.2f & %-10.2f  &%-10.2f  \n',...
    '13-bus','----', Method,NaN,...
    Network.Solution.OptimalValue, ...
NaN,...
Network.Solution.vMin,...
    Network.Solution.vMax,...
    Network.Solution.VoltageUnbalanceIndex,Network.Solution.MaxAngle,NaN, NaN);
 


end
 
